export enum JiraCustomFields {
  Summary = 'summary',
  Key = 'key',
  LegislativeTitle = 'customfield_14704',
  LegislativeSummary = 'customfield_13705',
  LegislativeDescription = 'customfield_14701',
  LegislativeSourceLinks = 'customfield_14702',
  LegislativeBusinessImpact = 'customfield_14700',
  LegislativeSystemImpact = 'customfield_14703',
  Attachments = 'attachment',
  Description = 'description',
  DueDate = 'duedate',
  FixVersions = 'fixVersions',
  ReleaseStatus = 'status',
  ApplicationArea = 'customfield_14600',
  specialNotes = 'customfield_15112',
}
