export enum JiraCustomFields {
  Summary = 'summary',
  Key = 'key',
  lTitle = 'customfield_14704',
  lSummary = 'customfield_13705',
  lDescription = 'customfield_14701',
  lSourceLinks = 'customfield_14702',
  lBusinessImpact = 'customfield_14700',
  lSystemImpact = 'customfield_14703',
  Attachments = 'attachment',
  Description = 'description',
  DueDate = 'duedate',
  FixVersions = 'fixVersions',
  ReleaseStatus = 'status',
  specialNotes = 'customfield_15112',
  project = 'project',
  ApplicationArea = 'customfield_14600',
  productLine = 'customfield_14601',
  SPT = 'customfield_14611',
  Country = 'customfield_14602',
  ConfigurationSteps = 'customfield_15200',
  UserGuide = 'customfield_15201',
}
